POST https://8z9bgrku83.execute-api.us-east-2.amazonaws.com/prod/story/predict
Content-Type: application/json
x-api-key: IDVn92bcvIar2OdrxSbAP1e1759rMwnlahDbmRKT

{
  "text": "Your input data for the model goes here"
}

###

GET https://gxmcil5kx4.execute-api.us-east-2.amazonaws.com/prod/
x-api-key: yvwvvhv4s5
