POST https://g0xznvd2ve.execute-api.us-east-2.amazonaws.com/prod/first/predict
Content-Type: application/json

{
    "text": "Hello, world! I really hope this works and the Cursor overloads are pleased."
}
